version: '3.2'

services:

  frontend_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: frontend
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev
#    command: gunicorn frontend.app:init_app -w 8 -b 0.0.0.0:8080 --worker-class aiohttp.GunicornUVLoopWebWorker

  postgres:
      image: postgres
      container_name: frontend_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432

  redis:
    image: redis
    ports:
        - 6379

  test:
    <<: *app
    container_name: frontend_test
    ports:
      - 8082:8082
    entrypoint: py.test -v -p no:warnings
    command: ''
